### PR TITLE
bump k8s to 1.26.1

### PR DESCRIPTION
**Pull request by rashmigottipati**

### CODE REVIEW

**Comment by rashmigottipati** [comment]
cc @grokspawn @everettraven @oceanc80

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by everettraven** [comment]
I think the test failures here are the same that @jberkhahn had encountered and lead to the creation of this issue: https://github.com/operator-framework/operator-sdk/issues/6303

I think this is good to merge in. I know @jberkhahn has the admin permissions needed to merge this but not sure who else does.

**Comment by rashmigottipati** [comment]
cc @jmrodri @varshaprasad96

**Review by varshaprasad96 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
