### PR TITLE
bump k8s deps to 1.25 and golang to 1.19

### PR DESCRIPTION
**Pull request by laxmikantbpandhare**
bump k8s dependencies to 1.25 and golang to 1.19 `(apimachinery)`

### CODE REVIEW

**Comment by laxmikantbpandhare** [comment]
@everettraven @jmrodri PTAL

**Review by everettraven — APPROVED** [review]

**Comment by laxmikantbpandhare** [comment]
@zach-source Could you please take a look and merge this PR.

**Review by zach-source — APPROVED** [review]

**Pull request merged**
