### PR TITLE
Updating k8s to 1.31

### PR DESCRIPTION
**Pull request by Neo2308**
* Updated k8s dependencies to 1.31

Related to: https://github.com/operator-framework/operator-sdk/issues/6816

### CODE REVIEW

**Comment by Neo2308** [comment]
@everettraven / @acornett21 / @grokspawn / @zach-source could you help review this PR?

**Comment by acornett21** [comment]
I'm don't have access to this repo, but release for main should be cut before this is merged.

**Comment by Neo2308** [comment]
@zach-source can you help create a release for main (based on 1.30 change) so that we can merge this after that?

**Comment by Neo2308** [comment]
@grokspawn / @zach-source can you help merge this PR since v0.7.0 is released now.

**Pull request merged**
