### PR TITLE
Updating k8s to 1.30 & go to 1.22

### PR DESCRIPTION
**Pull request by Neo2308**
* Updated k8s dependencies to 1.30
* Updated golang version to 1.22.2

Related to: https://github.com/operator-framework/operator-sdk/issues/6730

### CODE REVIEW

**Comment by Neo2308** [comment]
@zach-source could you review this PR?
cc: @everettraven

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by everettraven** [comment]
@joelanford @kevinrizza do either of you have write access to this repo to merge this?

**Comment by Neo2308** [comment]
@grokspawn / @zach-source could you help merge this PR?

**Pull request merged**
