### PR TITLE
updating k8s to 1.28 and go to 1.20

### PR DESCRIPTION
**Pull request by acornett21**
- updating to k8s 1.28
- updating go to 1.20
- updating build GH go action to v4 and read from mod file
- Relates: operator-framework/operator-sdk#6554

### CODE REVIEW

**Review by everettraven — APPROVED** [review]

**Comment by everettraven** [comment]
I don't have write access to this repo so I can't merge this PR. Maybe @joelanford has write perms here?

**Comment by Neo2308** [comment]
Could someone help merge this PR?
This is blocking progress on https://github.com/operator-framework/operator-sdk/issues/6554

**Comment by Neo2308** [comment]
@grokspawn could you help merge this PR?

**Comment by zach-source** [comment]
Apologies - I'll merge today.

**Pull request merged**
